version: '3.12'

services:
  app:
    build:
      context: .
    command: >
      sh -c "python manage.py wait_for_db &&
             python manage.py migrate &&
             python manage.py runserver 0.0.0.0:8000"
    ports:
      - 8000:8000
    volumes:
      - ./app:/app
      - ./data/web:/vol/web
    environment:
      - DEBUG=1
      - DB_HOST=db
      - DB_NAME=ecollector
      - DB_USERNAME=postgres
      - DB_PASSWORD=Patryk1996.
    depends_on:
      - db

  db:
    image: postgres:13-alpine
    environment:
      - POSTGRES_DB=ecollector
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=Patryk1996.
