# Generated by Django 5.0.2 on 2024-04-27 01:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0002_card_user"),
    ]

    operations = [
        migrations.AddField(
            model_name="card",
            name="additional_attributes",
            field=models.JSONField(default={}),
        ),
        migrations.AddField(
            model_name="user",
            name="fields_to_show_on_list",
            field=models.JSONField(default={}),
        ),
    ]
