# Generated by Django 5.0.2 on 2024-05-04 13:27

import api.models
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0003_card_additional_attributes_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="PendingCard",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=64)),
                ("awers", models.ImageField(upload_to=api.models.card_image_file_path)),
                (
                    "rewers",
                    models.ImageField(upload_to=api.models.card_image_file_path),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
    ]
