# Generated by Django 5.0.2 on 2024-05-06 12:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0004_pendingcard"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="user",
            name="fields_to_show_on_list",
        ),
        migrations.AddField(
            model_name="user",
            name="fields_to_show",
            field=models.JSONField(
                blank=True,
                default={
                    "customFields": [],
                    "optionalFields": {
                        "chip_type": True,
                        "expiration_date": True,
                        "gsm_operator": True,
                        "magnetic_stripe_width": True,
                        "material_type": True,
                        "nr_of_pulses": True,
                        "number_printype": True,
                        "number_type": True,
                        "prefix": True,
                        "price": True,
                        "printed_amount": True,
                        "producer": True,
                        "production_date": True,
                        "publisher": True,
                        "series": True,
                        "shape": True,
                        "surface_type": True,
                    },
                },
            ),
        ),
        migrations.AlterField(
            model_name="card",
            name="additional_attributes",
            field=models.JSONField(blank=True, default={}),
        ),
    ]
