# Generated by Django 5.0.2 on 2024-05-18 11:48

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0005_remove_user_fields_to_show_on_list_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="card",
            name="additional_attributes",
        ),
        migrations.RemoveField(
            model_name="user",
            name="fields_to_show",
        ),
        migrations.AddField(
            model_name="card",
            name="type",
            field=models.CharField(
                choices=[
                    ("MAGNETIC", "Magnetic"),
                    ("CHIP", "Chip"),
                    ("GSM_STARTERS", "Gsm Starters"),
                    ("GSM_TOP_UPS", "Gsm Top Ups"),
                    ("ASSOCIATED_WITH_TELEPHONY", "Associated With Telephony"),
                    ("OTHER_TOP_UPS", "Other Top Ups"),
                    ("POLONIA", "Polonia"),
                    ("OTHER", "Other"),
                ],
                default="OTHER",
                max_length=32,
            ),
        ),
        migrations.AddField(
            model_name="card",
            name="value",
            field=models.DecimalField(
                blank=True, decimal_places=2, default=0, max_digits=8
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="user",
            name="catalog_number",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="user",
            name="chip_type",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="user",
            name="comment",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="user",
            name="expiration_date",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="user",
            name="gsm_operator",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="user",
            name="magnetic_stripe_width",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="user",
            name="material_type",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="user",
            name="nr_of_pulses",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="user",
            name="number_printype",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="user",
            name="number_type",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="user",
            name="prefix",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="user",
            name="price",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="user",
            name="printed_amount",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="user",
            name="producer",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="user",
            name="production_date",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="user",
            name="publisher",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="user",
            name="series",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="user",
            name="shape",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="user",
            name="surface_type",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="user",
            name="value",
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name="card",
            name="catalog_number",
            field=models.CharField(blank=True, max_length=128),
        ),
        migrations.AlterField(
            model_name="card",
            name="chip_type",
            field=models.CharField(
                blank=True,
                choices=[
                    ("MANUFACTURER", "Manufacturer"),
                    ("PATTERN", "Pattern"),
                    ("IMAGE", "Image"),
                ],
                max_length=32,
            ),
        ),
        migrations.AlterField(
            model_name="card",
            name="comment",
            field=models.CharField(blank=True, max_length=512),
        ),
        migrations.AlterField(
            model_name="card",
            name="expiration_date",
            field=models.DateField(blank=True),
        ),
        migrations.AlterField(
            model_name="card",
            name="gsm_operator",
            field=models.CharField(
                blank=True,
                choices=[
                    ("ERA", "Era"),
                    ("TAK_TAK", "Tak Tak"),
                    ("IDEA", "Idea"),
                    ("POP", "Pop"),
                    ("ORANGE", "Orange"),
                    ("PLUS", "Plus"),
                    ("SIMPLUS", "Simplus"),
                    ("PLUSH", "Plush"),
                    ("HEYAH", "Heyah"),
                    ("PLAY", "Play"),
                    ("REDBULL", "Redbull"),
                    ("OTHER", "Other"),
                ],
                max_length=32,
            ),
        ),
        migrations.AlterField(
            model_name="card",
            name="magnetic_stripe_width",
            field=models.CharField(blank=True, max_length=64),
        ),
        migrations.AlterField(
            model_name="card",
            name="material_type",
            field=models.CharField(
                blank=True,
                choices=[
                    ("CARTOON", "Cartoon"),
                    ("PLASTIC", "Plastic"),
                    ("OTHER", "Other"),
                ],
                max_length=32,
            ),
        ),
        migrations.AlterField(
            model_name="card",
            name="nr_of_pulses",
            field=models.IntegerField(
                blank=True,
                choices=[
                    (5, "Five"),
                    (10, "Ten"),
                    (15, "Fifteen"),
                    (20, "Twenty"),
                    (25, "Twenty Five"),
                    (30, "Thirty"),
                    (35, "Thirty Five"),
                    (50, "Fifty"),
                    (100, "One Hundred"),
                    (150, "One Hundred Fifty"),
                    (200, "Two Hundred"),
                ],
            ),
        ),
        migrations.AlterField(
            model_name="card",
            name="number_printype",
            field=models.CharField(
                blank=True,
                choices=[
                    ("EMBOSSED_HORIZONTAL", "Embossed Horizontal"),
                    ("EMBOSSED_VERTICAL", "Embossed Vertical"),
                    ("PRINTED_HORIZONTAL", "Printed Horizontal"),
                    ("PRINTED_VERTICAL", "Printed Vertical"),
                ],
                max_length=32,
            ),
        ),
        migrations.AlterField(
            model_name="card",
            name="number_type",
            field=models.CharField(blank=True, max_length=64),
        ),
        migrations.AlterField(
            model_name="card",
            name="prefix",
            field=models.PositiveBigIntegerField(
                blank=True,
                validators=[
                    django.core.validators.MinValueValidator(100),
                    django.core.validators.MaxValueValidator(9999),
                ],
            ),
        ),
        migrations.AlterField(
            model_name="card",
            name="price",
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=8),
        ),
        migrations.AlterField(
            model_name="card",
            name="printed_amount",
            field=models.CharField(blank=True, max_length=64),
        ),
        migrations.AlterField(
            model_name="card",
            name="producer",
            field=models.CharField(blank=True, max_length=64),
        ),
        migrations.AlterField(
            model_name="card",
            name="production_date",
            field=models.DateField(blank=True),
        ),
        migrations.AlterField(
            model_name="card",
            name="publisher",
            field=models.CharField(blank=True, max_length=64),
        ),
        migrations.AlterField(
            model_name="card",
            name="series",
            field=models.CharField(blank=True, max_length=64),
        ),
        migrations.AlterField(
            model_name="card",
            name="shape",
            field=models.CharField(
                blank=True,
                choices=[
                    ("RECTANGLE", "Rectangle"),
                    ("CIRCLE", "Circle"),
                    ("HEART", "Heart"),
                    ("OTHER", "Other"),
                ],
                max_length=32,
            ),
        ),
        migrations.AlterField(
            model_name="card",
            name="surface_type",
            field=models.CharField(
                blank=True,
                choices=[
                    ("MAT", "Mat"),
                    ("GLOSS", "Gloss"),
                    ("COATED", "Coated"),
                    ("MAT_COATED", "Mat Coated"),
                    ("OTHER", "Other"),
                ],
                max_length=32,
            ),
        ),
    ]
