# Generated by Django 5.0.2 on 2024-05-18 18:51

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0006_remove_card_additional_attributes_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="pendingcard",
            name="type",
            field=models.CharField(
                choices=[
                    ("MAGNETIC", "Magnetic"),
                    ("CHIP", "Chip"),
                    ("GSM", "Gsm"),
                    ("ASSOCIATED_WITH_TELEPHONY", "Associated With Telephony"),
                    ("OTHER_TOP_UPS", "Other Top Ups"),
                    ("POLONIA", "Polonia"),
                    ("OTHER", "Other"),
                ],
                default="OTHER",
                max_length=32,
            ),
        ),
        migrations.AlterField(
            model_name="card",
            name="expiration_date",
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="card",
            name="nr_of_pulses",
            field=models.IntegerField(
                blank=True,
                choices=[
                    (5, "Five"),
                    (10, "Ten"),
                    (15, "Fifteen"),
                    (20, "Twenty"),
                    (25, "Twenty Five"),
                    (30, "Thirty"),
                    (35, "Thirty Five"),
                    (50, "Fifty"),
                    (100, "One Hundred"),
                    (150, "One Hundred Fifty"),
                    (200, "Two Hundred"),
                ],
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="card",
            name="prefix",
            field=models.PositiveBigIntegerField(
                blank=True,
                null=True,
                validators=[
                    django.core.validators.MinValueValidator(100),
                    django.core.validators.MaxValueValidator(9999),
                ],
            ),
        ),
        migrations.AlterField(
            model_name="card",
            name="price",
            field=models.DecimalField(
                blank=True, decimal_places=2, max_digits=8, null=True
            ),
        ),
        migrations.AlterField(
            model_name="card",
            name="production_date",
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="card",
            name="type",
            field=models.CharField(
                choices=[
                    ("MAGNETIC", "Magnetic"),
                    ("CHIP", "Chip"),
                    ("GSM", "Gsm"),
                    ("ASSOCIATED_WITH_TELEPHONY", "Associated With Telephony"),
                    ("OTHER_TOP_UPS", "Other Top Ups"),
                    ("POLONIA", "Polonia"),
                    ("OTHER", "Other"),
                ],
                default="OTHER",
                max_length=32,
            ),
        ),
        migrations.AlterField(
            model_name="card",
            name="value",
            field=models.DecimalField(
                blank=True, decimal_places=2, max_digits=8, null=True
            ),
        ),
        migrations.AlterField(
            model_name="user",
            name="comment",
            field=models.BooleanField(default=True),
        ),
    ]
